# **"Guess the year" miniproject III**
**(Baglan AITU)**

In [ ]:
# Required libraries

import pandas as pd
import torch as t
import torch.nn as nn
from sklearn.model_selection import train_test_split

In [ ]:
# Loading the dataset
data = pd.read_csv("/content/YearPredictionMSD.csv")
data.head()

0         1         2         3  ...         87        88         89        90
0  2001  49.94357  21.47114  73.07750  ...   68.40795  -1.82223  -27.46348   2.26327
1  2001  48.73215  18.42930  70.32679  ...   70.49388  12.04941   58.43453  26.92061
2  2001  50.95714  31.85602  55.81851  ... -115.00698  -0.05859   39.67068  -0.66345
3  2001  48.24750  -1.89837  36.29772  ...  -72.08993   9.90558  199.62971  18.85382
4  2001  50.97020  42.20998  67.09964  ...   51.76631   7.88713   55.66926  28.74903

[5 rows x 91 columns]

In [ ]:
# Check for categorical features

cols = data.columns
num_cols = data._get_numeric_data().columns
categorical=list(set(cols) - set(num_cols))
print(categorical)

[]


In [ ]:
# Check for missing values

data.isnull().sum()

0     0
1     0
2     0
3     0
4     0
     ..
86    0
87    0
88    0
89    0
90    0
Length: 91, dtype: int64

In [ ]:
# Checking fot Outliers

outliers = {}
for i in range(data.shape[1]):
  min_t = data[data.columns[i]].mean()- (3 *
data[data.columns[i]].std())
  max_t = data[data.columns[i]].mean()+ (3 *
data[data.columns[i]].std())
  count = 0
  for j in data[data.columns[i]]:
    if j < min_t or j > max_t:
      count += 1
  percentage = count / data.shape[0]
  outliers[data.columns[i]] = "%.3f" % percentage
outliers

{'0': '0.019',
 '1': '0.010',
 '10': '0.005',
 '11': '0.010',
 '12': '0.010',
 '13': '0.015',
 '14': '0.017',
 '15': '0.016',
 '16': '0.016',
 '17': '0.014',
 '18': '0.016',
 '19': '0.013',
 '2': '0.011',
 '20': '0.016',
 '21': '0.015',
 '22': '0.013',
 '23': '0.015',
 '24': '0.013',
 '25': '0.018',
 '26': '0.017',
 '27': '0.017',
 '28': '0.018',
 '29': '0.017',
 '3': '0.011',
 '30': '0.016',
 '31': '0.015',
 '32': '0.017',
 '33': '0.016',
 '34': '0.015',
 '35': '0.016',
 '36': '0.017',
 '37': '0.017',
 '38': '0.016',
 '39': '0.015',
 '4': '0.015',
 '40': '0.017',
 '41': '0.017',
 '42': '0.015',
 '43': '0.014',
 '44': '0.016',
 '45': '0.015',
 '46': '0.017',
 '47': '0.017',
 '48': '0.017',
 '49': '0.015',
 '5': '0.008',
 '50': '0.016',
 '51': '0.015',
 '52': '0.015',
 '53': '0.015',
 '54': '0.016',
 '55': '0.018',
 '56': '0.017',
 '57': '0.016',
 '58': '0.013',
 '59': '0.016',
 '6': '0.010',
 '60': '0.016',
 '61': '0.015',
 '62': '0.016',
 '63': '0.017',
 '64': '0.017',
 '65': '0.016',

In [ ]:
# Data Rescaling

X = data.iloc[:, 1:]
Y = data.iloc[:, 0]
X = (X - X.mean()) / X.std() # -average /std
X.head()

1         2         3  ...        88        89        90
0  1.082657  0.382437  1.841985  ... -0.467668 -0.247579  0.036872
1  0.880874  0.321953  1.763666  ...  0.573191  0.209887  1.155171
2  1.251484  0.588929  1.350579  ... -0.335333  0.109957 -0.095865
3  0.800148 -0.082240  0.794774  ...  0.412329  0.961849  0.789313
4  1.253660  0.794806  1.671781  ...  0.260874  0.195160  1.238096

[5 rows x 90 columns]

In [ ]:
# Split data

X.shape
train_end = int(len(X) * 0.8)
dev_end = int(len(X) * 0.9)

X_shuffle = X.sample(frac=1, random_state=0)
Y_shuffle = Y.sample(frac=1, random_state=0)
x_train = X_shuffle.iloc[:train_end,:]
y_train = Y_shuffle.iloc[:train_end]

x_dev = X_shuffle.iloc[train_end:dev_end,:]
y_dev = Y_shuffle.iloc[train_end:dev_end]
x_test = X_shuffle.iloc[dev_end:,:]
y_test = Y_shuffle.iloc[dev_end:]
print(x_train.shape, y_train.shape)
print(x_dev.shape, y_dev.shape)
print(x_test.shape, y_test.shape)

(40000, 90) (40000,)
(5000, 90) (5000,)
(5000, 90) (5000,)


In [ ]:
# Transform variables (be careful with cells, otherwise you will overwrite and obtain errors)

x_train = t.tensor(x_train.values).float()
y_train = t.tensor(y_train.values).float()
x_dev = t.tensor(x_dev.values).float()
y_dev = t.tensor(y_dev.values).float()
x_test = t.tensor(x_test.values).float()
y_test = t.tensor(y_test.values).float()

# Model

In [ ]:
# Define a model

model = nn.Sequential(nn.Linear(x_train.shape[1], 100), nn.ReLU(), nn.Linear(100,50), nn.ReLU(), nn.Linear(50,25), nn.ReLU(), nn.Linear(25, 1))

In [ ]:
# Define the loss function and the optimizer

loss_function = t.nn.MSELoss()
optimizer = t.optim.Adam(model.parameters(), lr=0.05) 

In [ ]:
print(x_train)
print(y_dev)
print(y_train)

tensor([[-1.0826e+00, -1.1189e+00, -1.5053e+00,  ..., -5.6287e-01,
         -2.8907e-02, -9.2232e-02],
        [-4.5963e-03, -1.1776e+00,  4.8098e-01,  ..., -4.4235e-01,
          1.5350e-02,  3.5314e-01],
        [-3.0845e-01, -1.0612e+00,  7.3594e-01,  ...,  1.0330e+00,
         -1.6869e-01,  7.7626e-01],
        ...,
        [ 5.1204e-01, -7.7624e-01, -1.1353e+00,  ...,  2.0932e+00,
          5.7537e+00,  3.6338e+00],
        [ 5.8048e-01,  9.7457e-01,  5.7132e-01,  ..., -2.4436e-01,
         -5.5204e-01, -4.3567e-02],
        [-7.0243e-01, -4.9564e-01,  1.2523e+00,  ..., -1.1171e+00,
          4.5657e-01,  2.8556e+00]])
tensor([1997., 2001., 2006.,  ..., 2001., 1991., 2005.])
tensor([2006., 1987., 1963.,  ..., 2008., 2008., 1976.])


In [ ]:
EPOCHS=3000
for i in range(EPOCHS):
  y_pred = model(x_train).squeeze()
  loss = loss_function(y_pred, y_train)
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()
  if i%100 == 0:
    print(i, loss.item())

0 3993159.25
100 51213.63671875
200 1123.68603515625
300 223.20884704589844
400 137.2587432861328
500 111.54052734375
600 207.18006896972656
700 130.26210021972656
800 634.787109375
900 149.55386352539062
1000 91.93426513671875
1100 88.77936553955078
1200 119.93938446044922
1300 92.69599151611328
1400 83.3357162475586
1500 110.73416137695312
1600 306.3379821777344
1700 4533.544921875
1800 2343.12451171875
1900 580.8319702148438
2000 782.9967651367188
2100 171.38429260253906
2200 742.2029418945312
2300 1488.1324462890625
2400 1810.604248046875
2500 589.7868041992188
2600 279.13623046875
2700 1529.811279296875
2800 583.5845947265625
2900 10888.0498046875


In [ ]:
# we didn't use accuracy because it is not classification problem. Number of epochs increase the prediction

pred = model(x_test[0])
print("Ground truth:", y_test[0].item(), "Prediction:",pred.item())

Ground truth: 2005.0 Prediction: 2003.466552734375
